language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
before_script:
- npm link .
script:
- "./ci/test.js"
- "./ci/travis/publish.js"
env:
  secure: "k08EKk+ksFPPaJ5B7GxpcKnNO+foUE0XgfldA8zfqAZj9LAUtWFcITyacxz+YwBIfSzxHaRi9gVk6ZZsB5ckhlB/wKeZ36uKoWt0zMihSYvIv9NOE07rgEBngJo+YafIOB7qpllLGXU+3WjWgopfpB/x5GCEeiyx0/IbCYUz3mGAe4ikbUk7QuiVTj+2o8O6wNLGDzONiqpOwl7TxH8mt9AkyIYhsT8qWxJgqhHmHMc90BpySPsy9n/rkTJw5qz+zUkiye6LI+yFMyq594fO3GPgAS3bi8N1rCccAMKPIStdhffPb60hpOFj8fJ5h70HRbt+9FjHo5UR9ZIPiTpnRQmK+RSDyNgop8qJKC4ij8MbR1X7snmP2XWiUbiT+kQVe1bAbivcnM65bQY1QDxGVW7pw80ik1buZtkvGIljsRbYr7zLKxNqbQulvmzbutw95bk7zg9kUVfNZPIdioTg3xQtn3FULkY+w1FaA7LUwrvOaYEwBkUTuf08YseAfaEi12vw0KteaI85VCkyP3Zo86BXX7k7Fw7mVu/azv0pPoEQ3L7v4w1sE1somETlWfY3GkIZOImtIkJZ36V9TwPLQOORVpveTz2a9O4EIDMTI3Uu2E2gTAb/LeiqRB/YtUZ5fGDqDC3QS5jqNbKtqatful1t/xklIevK1PFCLSYU0E4="