language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
before_script:
- npm link .
script:
- "./ci/test.js"
- "./ci/travis/publish.js"
env:
  secure: "O/HujJY0HZFJTHbtw9+c2E2RPWa9zzbZ7H8VZDGXwf/lwm76sCtGjPIzfwO/NZgyxv3C+L+l6CCtf1viuc0r4TDRL8+UHUYlz4bilxcVybrMIG4wL5d2LiBEE2NYTRAy2pQtmn0Tss5fTuYVmH6QcKteob8IGfAMf31e3rU0/PYWzMRoO1GQ62XGOkKnQYgWMWbMR0DawyunvlDgrvQUkQqpVyqh+YSndJNrIky7eihhNU/C5gl6J89q4j638WITiWpRC6vUUi93kEtnyz4tgBD5eBXENN6Tn4iaXDhPb/Ie6Ei7DBJjlW998NLTo+CE4aq1v2r8VF5Z0LiQS5zv2KbwKtwZeLH2xqKk/BuKirgYYuCC3Jvc/m7TGSFHax+EWB3hBdynyN2c0FacgnNuOgbsSnd4TJqgTCgRz8LjyBAd3skROCtI3rWhG7NHa18XN6adnj7dP9DlKjzt8kpmjw6veVaFdg87XcqG/+uvDjskuHKciBLuonNeqdb2NY2mQQHc/UQ0+uOOVR46w4ABjIjpbssizvfcUt9M6lW3wtXyPCxNHud9Er4PAePalA5tkzzkeqdS0cuc5RudUnbXTUzUmX82LO502DGw2+BfinbokXHeUwCj3Pynk9QDcXS9lq+yucTWrGPpJFXLwL+l9rqvDm4RDn+z1nS5GnT4s/U="